// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241127090256_PlanQRDBVersion1.3")]
    partial class PlanQRDBVersion13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Domain.Chat", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Domain.Lesson", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("degreeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("end")
                        .HasColumnType("TEXT");

                    b.Property<string>("faculty")
                        .HasColumnType("TEXT");

                    b.Property<string>("fieldStudies")
                        .HasColumnType("TEXT");

                    b.Property<string>("lecturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("room")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("roomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("speciality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("start")
                        .HasColumnType("TEXT");

                    b.Property<string>("subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<string>("typeShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("typeStudy")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Chatid")
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("lecturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("room")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("roomId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Chatid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.HasOne("Domain.Chat", null)
                        .WithMany("messages")
                        .HasForeignKey("Chatid");
                });

            modelBuilder.Entity("Domain.Chat", b =>
                {
                    b.Navigation("messages");
                });
#pragma warning restore 612, 618
        }
    }
}
